"""
Generates postgis/adm.sql.gz — the database for part 2 of the workshop.

A small "gold product" the way it would sit in a real PostGIS database: its own
schema (adm), primary and foreign keys, spatial indexes, and comments on every
table and column. Geometries are full detail in EPSG:25833.

  adm.fylker    15 counties
  adm.kommuner  357 municipalities  (→ adm.fylker)
  adm.byer      25 towns            (→ adm.kommuner)

The PostGIS container loads the file the first time it starts (it's mounted
into /docker-entrypoint-initdb.d, see docker-compose.yml).

Re-run to regenerate (needs shapely and pyproj):

    python3 tools/make_demo_dump.py
"""

import gzip
from pathlib import Path

import shapely
from pyproj import Transformer

from make_demo_gpkg import DUMPS, EPSG, TOWNS, as_multipolygons, read_dump

OUT = Path(__file__).resolve().parent.parent / "postgis" / "adm.sql.gz"

HEADER = """\
-- Generated by tools/make_demo_dump.py — the database for part 2 of the OGC API workshop.
-- Source: Kartverket, Administrative enheter (fylker og kommuner).

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE SCHEMA adm;
COMMENT ON SCHEMA adm IS 'Administrative enheter: fylker, kommuner og et utvalg byer.';

CREATE TABLE adm.fylker (
    fylkesnummer    text PRIMARY KEY,
    navn            text NOT NULL,
    antall_kommuner integer NOT NULL,
    areal_km2       double precision NOT NULL,
    geom            geometry(MultiPolygon, 25833) NOT NULL
);
COMMENT ON TABLE adm.fylker IS 'Norges fylker (inndelingen fra 2024). Kilde: Kartverket, Administrative enheter – fylker.';
COMMENT ON COLUMN adm.fylker.fylkesnummer IS 'Fylkesnummer, to sifre';
COMMENT ON COLUMN adm.fylker.navn IS 'Fylkets navn';
COMMENT ON COLUMN adm.fylker.antall_kommuner IS 'Antall kommuner i fylket';
COMMENT ON COLUMN adm.fylker.areal_km2 IS 'Areal i km², inkludert sjøareal innenfor grunnlinjen';
COMMENT ON COLUMN adm.fylker.geom IS 'Fylkesgrensen';

CREATE TABLE adm.kommuner (
    kommunenummer text PRIMARY KEY,
    navn          text NOT NULL,
    fylkesnummer  text NOT NULL REFERENCES adm.fylker,
    fylke         text NOT NULL,
    areal_km2     double precision NOT NULL,
    geom          geometry(MultiPolygon, 25833) NOT NULL
);
COMMENT ON TABLE adm.kommuner IS 'Norges kommuner (inndelingen fra 2024). Kilde: Kartverket, Administrative enheter – kommuner.';
COMMENT ON COLUMN adm.kommuner.kommunenummer IS 'Kommunenummer, fire sifre';
COMMENT ON COLUMN adm.kommuner.navn IS 'Kommunens navn';
COMMENT ON COLUMN adm.kommuner.fylkesnummer IS 'Fylket kommunen ligger i';
COMMENT ON COLUMN adm.kommuner.fylke IS 'Navnet på fylket kommunen ligger i';
COMMENT ON COLUMN adm.kommuner.areal_km2 IS 'Areal i km², inkludert sjøareal innenfor grunnlinjen';
COMMENT ON COLUMN adm.kommuner.geom IS 'Kommunegrensen';

CREATE TABLE adm.byer (
    id            integer PRIMARY KEY,
    navn          text NOT NULL,
    kommunenummer text NOT NULL REFERENCES adm.kommuner,
    kommune       text NOT NULL,
    fylke         text NOT NULL,
    geom          geometry(Point, 25833) NOT NULL
);
COMMENT ON TABLE adm.byer IS 'Et utvalg på 25 norske byer, plassert i bysentrum.';
COMMENT ON COLUMN adm.byer.id IS 'Løpenummer';
COMMENT ON COLUMN adm.byer.navn IS 'Byens navn';
COMMENT ON COLUMN adm.byer.kommunenummer IS 'Kommunen byen ligger i';
COMMENT ON COLUMN adm.byer.kommune IS 'Navnet på kommunen byen ligger i';
COMMENT ON COLUMN adm.byer.fylke IS 'Navnet på fylket byen ligger i';
COMMENT ON COLUMN adm.byer.geom IS 'Bysentrum';

"""

FOOTER = """
CREATE INDEX fylker_geom_idx ON adm.fylker USING gist (geom);
CREATE INDEX kommuner_geom_idx ON adm.kommuner USING gist (geom);
CREATE INDEX kommuner_fylkesnummer_idx ON adm.kommuner (fylkesnummer);
CREATE INDEX byer_geom_idx ON adm.byer USING gist (geom);
CREATE INDEX byer_kommunenummer_idx ON adm.byer (kommunenummer);

ANALYZE adm.fylker;
ANALYZE adm.kommuner;
ANALYZE adm.byer;
"""


def lit(value) -> str:
    """A Python value as an SQL literal."""
    if isinstance(value, str):
        return "'" + value.replace("'", "''") + "'"
    return repr(value)


def ewkb(geom) -> str:
    # Hex EWKB with the SRID — PostGIS reads this straight into a geometry column
    return "'" + shapely.to_wkb(shapely.set_srid(geom, EPSG), hex=True, include_srid=True) + "'"


def inserts(table: str, columns: list[str], rows: list[tuple]) -> str:
    cols = ", ".join(columns)
    return "".join(
        f"INSERT INTO adm.{table} ({cols}) VALUES ({', '.join(map(lit, r[:-1]))}, {ewkb(r[-1])});\n"
        for r in rows
    )


def main() -> None:
    fylker = sorted(read_dump(DUMPS["fylker"]))
    kommuner = sorted(read_dump(DUMPS["kommuner"]))
    fylke_navn = {nr: navn for nr, navn, _ in fylker}
    antall = {nr: sum(k[0][:2] == nr for k in kommuner) for nr, *_ in fylker}
    km2 = lambda g: round(g.area / 1e6, 1)

    to_utm = Transformer.from_crs(4326, EPSG, always_xy=True)
    byer = []
    for i, (navn, lon, lat) in enumerate(TOWNS, start=1):
        pt = shapely.Point(*to_utm.transform(lon, lat))
        knr, knavn, _ = next(k for k in kommuner if k[2].contains(pt))
        byer.append((i, navn, knr, knavn, fylke_navn[knr[:2]], pt))

    f_geoms = as_multipolygons([g for *_, g in fylker])
    k_geoms = as_multipolygons([g for *_, g in kommuner])

    sql = HEADER
    sql += inserts(
        "fylker", ["fylkesnummer", "navn", "antall_kommuner", "areal_km2", "geom"],
        [(nr, navn, antall[nr], km2(g), g) for (nr, navn, _), g in zip(fylker, f_geoms)],
    )
    sql += inserts(
        "kommuner", ["kommunenummer", "navn", "fylkesnummer", "fylke", "areal_km2", "geom"],
        [(nr, navn, nr[:2], fylke_navn[nr[:2]], km2(g), g) for (nr, navn, _), g in zip(kommuner, k_geoms)],
    )
    sql += inserts("byer", ["id", "navn", "kommunenummer", "kommune", "fylke", "geom"], byer)
    sql += FOOTER

    OUT.parent.mkdir(parents=True, exist_ok=True)
    # mtime=0 keeps the file byte-identical between runs with the same data
    with gzip.GzipFile(OUT, "wb", mtime=0) as f:
        f.write(sql.encode("utf-8"))
    print(f"Wrote {OUT}: {len(fylker)} fylker, {len(kommuner)} kommuner, {len(byer)} byer "
          f"({len(sql) / 1e6:.1f} MB SQL, {OUT.stat().st_size / 1e6:.1f} MB gzipped)")


if __name__ == "__main__":
    main()
